### ISSUE TITLE
(Mix) The database for Anykura.Repo couldn't be created: an exception was raised:Error 

### ISSUE THREAD

**Issue by flagmafun** [happysalada/bitly#1]
# 22:49:56.737 [error] GenServer #PID<0.1967.0> terminating
** (DBConnection.ConnectionError) tcp connect (localhost:5432): connection refused - :econnrefused
    (db_connection) lib/db_connection/connection.ex:163: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol
** (Mix) The database for Anykura.Repo couldn't be created: an exception was raised:
    ** (DBConnection.ConnectionError) tcp connect (localhost:5432): connection refused - :econnrefused
        (db_connection) lib/db_connection/connection.ex:163: DBConnection.Connection.connect/2
        (connection) lib/connection.ex:622: Connection.enter_connect/5
        (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3

# solution
mix deps.update postgrex

improved but not yet resolve

**Comment by Asuka52** [comment]
It worked!

On Mac OS to get up and running fast (with say Phoenix) simply run:

brew install postgresql && brew services start postgresql && psql postgres
then type:

CREATE ROLE postgres;
ALTER ROLE postgres WITH LOGIN;
ALTER USER postgres CREATEDB;
then CTRL & D
then mix ecto.create

**Comment by Asuka52** [comment]
But it occered.

Asuka@Asukas-MacBook-Pro:~/app/bitly (master *)$ mix ecto.create
The database for Anykura.Repo has been created
Asuka@Asukas-MacBook-Pro:~/app/bitly (master *)$ mix ecto.setup
The database for Anykura.Repo has already been created
** (Mix) Could not find migrations directory "/Users/Asuka/app/bitly/priv/repo/migrations"
for repo Anykura.Repo.

This may be because you are in a new project and the
migration directory has not been created yet. Creating an
empty directory at the path above will fix this error.

If you expected existing migrations to be found, please
make sure your repository has been properly configured
and the configured path exists.

**Comment by Asuka52** [comment]
So you should make .gitkeep

$ vim priv/repo/migrations/.gitkeep

$ mix ecto.create && mix ecto.migrate
The database for Anykura.Repo has already been created
[info] Already up

Done!
